services:
  db:
    image: postgres:15
    container_name: teamflow_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teamflow
    ports:
      - "5432:5432"
    volumes:
      - teamflow_pgdata:/var/lib/postgresql/data   # ✅ OLD DATA
      # ❌ REMOVE init.sql

  backend:
    build: ./backend
    container_name: teamflow_backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: udaifaudhu9483
      DB_NAME: teamflow
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: teamflow_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  teamflow_pgdata: