FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

# ✅ MUST
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]